version: "3.8"

services:
  db:
    image: postgres:13
    container_name: my_postgres
    environment:
      POSTGRES_DB: esplidwais-db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

volumes:
  postgres_data:
